import os

MATTER_TOKEN_ADDRESS = os.getenv("MATTER_TOKEN_ADDRESS", None)
print(f"MATTER_TOKEN_ADDRESS: {MATTER_TOKEN_ADDRESS}")
IDEA_TOKEN_ADDRESS = os.getenv("IDEA_TOKEN_ADDRESS", None)
print(f"IDEA_TOKEN_ADDRESS: {IDEA_TOKEN_ADDRESS}")
USDT_TOKEN_ADDRESS = os.getenv("USDT_TOKEN_ADDRESS", None)
print(f"USDT_TOKEN_ADDRESS: {USDT_TOKEN_ADDRESS}")

STABLECOIN_ADDRESSES = {
    'USDT': '0x55d398326f99059fF775485246999027b3197955',
    'USDC': '0x8ac76a51cc950d9822d68b83fe1ad97b32cd580d',
    'BUSD': '0xe9e7cea3dedca5984780bafc599bd69add087d56',
    'DAI': '0x1af3f329e8be154074d8769d1ffa4ee058b1dbc3'
}
APP_WALLET = os.getenv("APP_WALLET", None)
print(f"APP_WALLET: {APP_WALLET}")
APP_WALLET_PRIVATE_KEY = os.getenv("APP_WALLET_PRIVATE_KEY", None)
print(f"APP_WALLET_PRIVATE_KEY: {APP_WALLET_PRIVATE_KEY}")
TON_API_KEY = os.getenv("TON_API_KEY", None)
print(f"TON_API_KEY: {TON_API_KEY}")
INFURA_API_KEY = os.getenv("INFURA_API_KEY", None)
print(f"INFURA_API_KEY: {INFURA_API_KEY}")
MORALIS_API_KEY = os.getenv("MORALIS_API_KEY", None)
print(f"MORALIS_API_KEY: {MORALIS_API_KEY}")
BSC_API_KEY = os.getenv("BSC_API_KEY", None)
print(f"BSC_API_KEY: {BSC_API_KEY}")
PANCAKESWAP_ROUTER_ADDRESS = os.getenv("PANCAKESWAP_ROUTER_ADDRESS", None)
print(f"PANCAKESWAP_ROUTER_ADDRESS: {PANCAKESWAP_ROUTER_ADDRESS}")
