# Generated by Django 5.1.2 on 2025-06-09 08:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.IntegerField(choices=[(0, 'Closed'), (1, 'Open'), (2, 'Freeze')], default=1)),
                ('block_hash', models.CharField(max_length=64)),
                ('prev_block_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('idea_price', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bet_size', models.DecimalField(decimal_places=8, max_digits=18)),
                ('bet_percent', models.DecimalField(decimal_places=8, max_digits=18)),
                ('start_matter_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('start_idea_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('is_active', models.BooleanField(default=True)),
                ('is_winning', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bet_ratio', models.DecimalField(blank=True, decimal_places=8, default=0, max_digits=18, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('type', models.IntegerField(choices=[(0, 'Withdrawal'), (1, 'Deposit')], default=1)),
                ('from_wallet', models.CharField(max_length=74)),
                ('to_wallet', models.CharField(max_length=74)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bet')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.block')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_wallet_address', models.CharField(blank=True, max_length=74, null=True)),
                ('crypto_wallet_private_key', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
