import os
from web3 import Web3

MATTER_TOKEN_ADDRESS = os.getenv("MATTER_TOKEN_ADDRESS", None)
print(f"MATTER_TOKEN_ADDRESS: {MATTER_TOKEN_ADDRESS}")
IDEA_TOKEN_ADDRESS = os.getenv("IDEA_TOKEN_ADDRESS", None)
print(f"IDEA_TOKEN_ADDRESS: {IDEA_TOKEN_ADDRESS}")
APP_WALLET = os.getenv("APP_WALLET", None)
print(f"APP_WALLET: {APP_WALLET}")
APP_WALLET_PRIVATE_KEY = os.getenv("APP_WALLET_PRIVATE_KEY", None)
print(f"APP_WALLET_PRIVATE_KEY: {APP_WALLET_PRIVATE_KEY}")
TON_API_KEY = os.getenv("TON_API_KEY", None)
print(f"TON_API_KEY: {TON_API_KEY}")
INFURA_API_KEY = os.getenv("INFURA_API_KEY", None)
print(f"INFURA_API_KEY: {INFURA_API_KEY}")
MORALIS_API_KEY = os.getenv("MORALIS_API_KEY", None)
print(f"MORALIS_API_KEY: {MORALIS_API_KEY}")
BSC_API_KEY = os.getenv("BSC_API_KEY", None)
print(f"BSC_API_KEY: {BSC_API_KEY}")
BSC_RPC_URL = os.getenv("BSC_RPC_URL", "https://rpc.ankr.com/bsc")
print(f"BSC_RPC_URL: {BSC_RPC_URL}")
USDT_TOKEN_ADDRESS = Web3.to_checksum_address("0x55d398326f99059fF775485246999027b3197955")
print(f"USDT_TOKEN_ADDRESS: {USDT_TOKEN_ADDRESS}")
PANCAKESWAP_ROUTER_ADDRESS = os.getenv("PANCAKESWAP_ROUTER_ADDRESS", None)
print(f"PANCAKESWAP_ROUTER_ADDRESS: {PANCAKESWAP_ROUTER_ADDRESS}")
WALLETCONNECT_PROJECT_ID = os.getenv("WALLETCONNECT_PROJECT_ID", None)
print(f"WALLETCONNECT_PROJECT_ID: {WALLETCONNECT_PROJECT_ID}")

# Deposit addresses (можно переопределить через env переменные)
DEPOSIT_ADDRESS_TRC20 = os.getenv("DEPOSIT_ADDRESS_TRC20", "")
DEPOSIT_ADDRESS_BSC = os.getenv("DEPOSIT_ADDRESS_BSC", "")
DEPOSIT_ADDRESS_TON = os.getenv("DEPOSIT_ADDRESS_TON", "")
DEPOSIT_ADDRESS_BYBIT = os.getenv("DEPOSIT_ADDRESS_BYBIT", "")

print(f"DEPOSIT_ADDRESS_TRC20: {DEPOSIT_ADDRESS_TRC20}")
print(f"DEPOSIT_ADDRESS_BSC: {DEPOSIT_ADDRESS_BSC}")
print(f"DEPOSIT_ADDRESS_TON: {DEPOSIT_ADDRESS_TON}")
print(f"DEPOSIT_ADDRESS_BYBIT: {DEPOSIT_ADDRESS_BYBIT}")

# Withdrawal settings (приватные ключи от кошельков для отправки)
WITHDRAW_PRIVATE_KEY_TRC20 = os.getenv("WITHDRAW_PRIVATE_KEY_TRC20", "")
WITHDRAW_PRIVATE_KEY_BSC = os.getenv("WITHDRAW_PRIVATE_KEY_BSC", "")
WITHDRAW_TON_MNEMONIC = os.getenv("WITHDRAW_TON_MNEMONIC", "")

# USDT TRC-20 contract address on Tron
USDT_TRC20_CONTRACT = "TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t"

# TronGrid API
TRONGRID_API_KEY = os.getenv("TRONGRID_API_KEY", "")
TRONGRID_API_URL = "https://api.trongrid.io"

# TON Configuration
USDT_TON_CONTRACT = os.getenv("USDT_TON_CONTRACT", "EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs")
TON_API_ENDPOINT = os.getenv("TON_API_ENDPOINT", "https://toncenter.com/api/v2")
